services:
    nginx:
        image: nginx:latest
        container_name: nginx
        restart: always
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        environment:
            - NGINX_PORT=${NGINX_PORT}
            - BACKEND_HOST=api
            - BACKEND_PORT=${SERVER_PORT}
            - PGADMIN_HOST=pgadmin
        ports:
            - ${NGINX_PORT}:${NGINX_PORT}
        depends_on:
            - api
            - redis

    mysql:
        image: mysql:latest
        restart: always
        volumes:
            - ./mysql-data:/var/lib/mysql
        ports:
            - "3306:3306"
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --log_bin_trust_function_creators=1
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        container_name: mysql

    redis:
        container_name: redis
        image: redis:latest
        restart: always
        ports:
        - 6379:6379
        volumes:
        - ./docker/data/redis:/data

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: pma
        links:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        restart: always
        ports:
            - "8081:80"

    api:
        container_name: api
        build: .
        ports:
            - ${SERVER_PORT}:${SERVER_PORT}
        volumes:
            - .:/var/www
        env_file:
            - .env
        depends_on:
            - mysql
            - redis
